name: Deploy React Loyalty Frontend application

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build docker image
        run: sudo docker build -t tengoshamugia/loyalty_frontend .
      - name: Login to docker hub
        run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
      - name: Publish image to docker hub
        run: sudo docker push tengoshamugia/loyalty_frontend:latest




  # deploy-1:
  #   needs: build
  #   runs-on: ["self-hosted", "first"]
  #   steps:
  #     - name: Stop old container
  #       run: sudo docker stop frontend || true

  #     - name: Remove old container
  #       run: sudo docker rm frontend || true

  #     - name: Remove unused images
  #       run: sudo docker image prune -f || true
      
  #     - name: Remove unused containers
  #       run: sudo docker container prune -f || true

  #     - name: Pull image from Docker Hub
  #       run: sudo docker pull tengoshamugia/loyalty_frontend:latest
      

      # - name: Run new Docker container
      #   run: sudo docker run -d -p 3000:3000  --name frontend tengoshamugia/loyalty_frontend


  deploy-2:
    needs: build
    runs-on: ["self-hosted", "second"]
    steps:
      - name: Stop old container
        run: sudo docker stop frontend || true

      - name: Remove old container
        run: sudo docker rm frontend || true

      - name: Remove unused images
        run: sudo docker image prune -f || true

      - name: Remove unused containers
        run: sudo docker container prune -f || true

      - name: Pull image from Docker Hub
        run: sudo docker pull tengoshamugia/loyalty_frontend:latest

      - name: Run new Docker container
        run: sudo docker run -d -p 3000:3000  --name frontend tengoshamugia/loyalty_frontend
